#!/bin/sh
cat << EOF
if background_image /boot/grub/background.png; then
  set color_normal=white/black
  set color_highlight=black/white
else
  set menu_color_normal=white/black
  set menu_color_highlight=black/white
fi
EOF
